In [2]:
import numpy as np

## eigen value, eigen vector
### A.v = lambda. v

In [3]:
A=np.array([[0.,1.] ,[-2.,-3.]])
A

array([[ 0.,  1.],
       [-2., -3.]])

In [4]:
eigvals, eigvecs = np.linalg.eig(A)

In [5]:
eigvals, eigvecs

(array([-1., -2.]), array([[ 0.70710678, -0.4472136 ],
        [-0.70710678,  0.89442719]]))

In [10]:
#lambda1 * v1 = A * v1
eigvals[0]*eigvecs[:,0] , A.dot(eigvecs[:,0])

(array([-0.70710678,  0.70710678]), array([-0.70710678,  0.70710678]))

In [11]:
eigvals[1]*eigvecs[:,1] , A.dot(eigvecs[:,1])

(array([ 0.89442719, -1.78885438]), array([ 0.89442719, -1.78885438]))

### LU decomposition

In [6]:
from scipy.linalg import lu

In [7]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#PLU Decomposition
P, L, U =lu(A)

In [15]:
P, L, U

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]), array([[1.        , 0.        , 0.        ],
        [0.14285714, 1.        , 0.        ],
        [0.57142857, 0.5       , 1.        ]]), array([[7.        , 8.        , 9.        ],
        [0.        , 0.85714286, 1.71428571],
        [0.        , 0.        , 0.        ]]))

In [18]:
B=P.dot(L).dot(U)
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
B=L.dot(U)
B

array([[7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.]])

### QR Decomposition

In [20]:
from scipy.linalg import qr

In [21]:
A=np.array([[1,2],[4,5],[7,8]])
A

array([[1, 2],
       [4, 5],
       [7, 8]])

In [22]:
Q, R= qr(A,mode='full')
Q, R

(array([[-0.12309149,  0.90453403,  0.40824829],
        [-0.49236596,  0.30151134, -0.81649658],
        [-0.86164044, -0.30151134,  0.40824829]]),
 array([[-8.1240384 , -9.6011363 ],
        [ 0.        ,  0.90453403],
        [ 0.        ,  0.        ]]))

In [23]:
Q.dot(R)

array([[1., 2.],
       [4., 5.],
       [7., 8.]])

In [26]:
#orthogoinality check
(Q[:,0]*Q[:,1]).sum(), (Q[:,1]*Q[:,2]).sum(), (Q[:,0]*Q[:,2]).sum()

(-2.220446049250313e-16, 1.3877787807814457e-17, 0.0)

In [28]:
#normality check
for i in range(3):
    vec=np.array(Q[:,i])
    print((vec**2).sum()) #norm 

1.0000000000000002
1.0000000000000002
1.0


### eigen deconposition

In [29]:
A =np.array([[6,2],[2,3]])
A

array([[6, 2],
       [2, 3]])

In [30]:
eigvals, eigvecs = np.linalg.eig(A)
eigvals, eigvecs

(array([7., 2.]), array([[ 0.89442719, -0.4472136 ],
        [ 0.4472136 ,  0.89442719]]))

In [34]:
np.diag(eigvals)

array([[7., 0.],
       [0., 2.]])

In [35]:
P = eigvecs
D = np.diag(eigvals)
P.dot(D).dot(P.T)

array([[6., 2.],
       [2., 3.]])

### SVD Decomposition

In [39]:
A=np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
U, S, VT = np.linalg.svd(A, full_matrices=True)
S

array([9.52551809, 0.51430058])

In [41]:
Smatrix = np.diag(S)
Smatrix = np.vstack([Smatrix,[0,0]])

In [42]:
U, Smatrix, VT

(array([[-0.2298477 ,  0.88346102,  0.40824829],
        [-0.52474482,  0.24078249, -0.81649658],
        [-0.81964194, -0.40189603,  0.40824829]]),
 array([[9.52551809, 0.        ],
        [0.        , 0.51430058],
        [0.        , 0.        ]]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))

In [43]:
U.dot(Smatrix).dot(VT)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

3